name: Test

on: 
  workflow_dispatch:
  push:
    tags:
      - '!v*'
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install the project
      run: |
        uv sync --all-extras --dev
        uv pip install .
    - name: Run tests
      run: uv run pytest tests